#!/bin/bash
ARGS=1
E_BADARGS=65
TEM_FILE="/tmp/dict.tmp"
 
if [ $# -lt "$ARGS" ]
 then
    echo "Usage:`basename $0` [word]"
    exit $E_BADARGS
fi

for i in $*
	do	
		if [ -z ${word} ]
		then
			word=$i
		else
			word=$word%20$i
		fi
done

echo $* >> ~/.usr_word.txt


curl -s 'http://dict.youdao.com/search?q='$word'' | awk 'BEGIN{j=0;i=0;} {if(/phrsListTab/){i++;} if(i==1){print $0; if(/<\/ul>/){i=0;}} if(/collinsToggle/){ j++;} if(j==1) {print $0; if(/<\/ul>/){j=0;}}}' | sed 's/<[^>]*>//g' | sed 's/&nbsp;//g'| sed 's/&rarr;//g' | sed 's/^\s*//g' | sed '/^$/d'> $TEM_FILE
 

is_head=true

is_enter=true

is_header=false

head="" 
body="" 
ln_item=0 
ln_eg=0 
 
while read line
do
    let ln_item++
    let ln_eg++
    num_flag=`echo "$line" | awk '/[0-9]+\.$/'`
    if [ "$num_flag" != "" ]; then 
        is_head=false 
        ln_item=0
    fi
 
    eg_flag=`echo "$line" | awk '/例：$/'` # '例：'开头
    if [ "$eg_flag" != "" ]; then
        ln_eg=0
    fi
 
    if $is_head ; then 						#Format headers
    	if [ "${line: -1}x" == "]x" ] ;then
        	head="$head $line"
        elif [ ${line: -1}x == "错x" ] ;then
        	head="$head"
        elif [ "$line" == "${word//%20/ }" ] ;then
        	head="$head\n$line"
        	if $is_header ; then
        		head="$head"
        		is_enter=false
        	fi
        	is_header=true
        elif $is_enter ;then
        	head="$head\n$line"
        else
        	head="$head $line"
        fi
    else
        if [ $ln_item == 0 ] ; then
            line="\033[32;1m\n\n$line\033[0m" # 释义编号
        elif [ $ln_item == 1 ] ; then
            line="\033[32;1m[$line]\033[0m" # 词性
        elif [ $ln_item == 2 ] ; then
            line="\033[1m$line\033[0m" # 释义 
        elif [ $ln_eg == 0 ] ; then
            line="\033[32;1m\n   $line\033[0m" # 例：
        elif [ $ln_eg == 1 ]; then
            line="\033[33m$line\033[0m" # 例句 
        elif [ $ln_eg == 2 ]; then
            line="\033[33m$line\033[0m" # 例句释义 
        fi
        body="$body $line"
    fi
done < $TEM_FILE
echo -e "\033[31;1m$head\033[0m $body"
 
exit 0
